# Generated by Django 2.1.3 on 2018-11-15 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('verifier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verifier_Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=1000)),
                ('verifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verifier.Verifier')),
            ],
        ),
    ]
