# Generated by Django 2.1.3 on 2018-11-15 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('verifiee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verifiee_Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=1000)),
                ('verifiee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verifiee.Verifiee')),
            ],
        ),
    ]
