# Generated by Django 2.1.2 on 2018-10-18 21:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.TextField()),
                ('location', models.URLField(blank=True, default=None, null=True)),
                ('status', models.CharField(choices=[('COMPLETE', 'Complete'), ('PENDING', 'Pending'), ('ERROR', 'Error')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Verifier_Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified', models.BooleanField(blank=True, null=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Contract')),
                ('verifier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Person')),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Person'),
        ),
    ]
