# Generated by Django 2.1.2 on 2018-10-19 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verifier_contract',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='verifier_contract',
            name='verifier',
        ),
        migrations.AddField(
            model_name='contract',
            name='verifiers',
            field=models.ManyToManyField(related_name='verifier', to='api.Person'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='whom', to='api.Person'),
        ),
        migrations.DeleteModel(
            name='Verifier_Contract',
        ),
    ]
