# Generated by Django 2.1.3 on 2018-11-15 04:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('verifier', '0001_initial'),
        ('verifiee', '0001_initial'),
        ('api', '0003_auto_20181019_0151'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingContract',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.BooleanField(blank=True, null=True)),
                ('data', models.TextField()),
                ('accepted', models.BooleanField(blank=True, null=True)),
                ('verification_type', models.CharField(choices=[('DEGREE', 'Degree Verification'), ('SSN', 'Social Security Number'), ('CREDIT', 'Credit Score'), ('ADDRESS', 'Address'), ('BIRTHDAY', 'Birthday')], max_length=8)),
                ('verifiee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verifiee.Verifiee')),
                ('verifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verifier.Verifier')),
            ],
        ),
    ]
