# Generated by Django 2.1.3 on 2018-11-15 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_pendingcontract'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pendingcontract',
            old_name='data',
            new_name='data_to_verify',
        ),
    ]
