# Generated by Django 2.1.3 on 2018-11-15 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20181115_0446'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pendingcontract',
            old_name='data_to_verify',
            new_name='linking_data',
        ),
    ]
