# Generated by Django 2.1.3 on 2018-11-15 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20181115_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingcontract',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='pendingcontract',
            name='verification_type',
            field=models.CharField(choices=[('DEGREE', 'Education'), ('SSN', 'Social Security Number'), ('CREDIT', 'Credit Score'), ('ADDRESS', 'Address'), ('BIRTHDAY', 'Birthday')], max_length=8),
        ),
        migrations.AlterField(
            model_name='pendingcontract',
            name='verifiee',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='verifiee.Verifiee'),
        ),
    ]
