# Generated by Django 2.1.3 on 2018-11-15 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20181115_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingcontract',
            name='address',
            field=models.CharField(default='YOOOO', max_length=10000),
            preserve_default=False,
        ),
    ]
